export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const LOGIN_REQUEST_FAIL = 'LOGIN_REQUEST_FAIL';

export const LOG_OUT_USER = 'LOG_OUT_USER';

export const PCPARTS_REQUEST = 'PCPARTS_REQUEST';
export const PCPARTS_REQUEST_SUCCESS = 'PCPARTS_REQUEST_SUCCESS';
export const PCPARTS_REQUEST_FAIL = 'PCPARTS_REQUEST_FAIL';
